apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dni-functions
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.dni-function: semver:~1.0
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dni-function
    spec:
      containers:
      - name: dni-function
        image: cmendibl3/dni:1.0.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dni-functions
spec:
  type: ClusterIP
  ports:
  - name:
    port: 80
  selector:
    app: dni-function
